version: '3.3'

services:
  mongo:
    image: mongo
    container_name: local-mongo-container
    ports:
      - "27017:27017"
    volumes:
      - /app:/data/db  # Optional: Mount a volume for persistent data

  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile  # Path to your Node.js Dockerfile
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/CourseApp  # Replace mydatabase with your database name
    depends_on:
      - mongo
