version: '3.3'

services:
  mongo:
    image: mongo
    container_name: local-mongo-container
    ports:
      - "27017:27017"
    volumes:
      - /mongo-data:/data/db

  node-app:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: node-app-container
    ports:
      - "3000:3000"
    environment:
     MONGO_URI: mongodb://mongo:27017/CourseApp
    depends_on:
      - mongo
